name: Push to dockerhub

on:
  push:
    branches:
      - '6-logout-flow-for-frontend'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
          
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag redthorx/pepm_frontend_local:$(date +%s) --tag redthorx/pepm_frontend_local:latest
      
      - name: Push Docker image
        run: docker push redthorx/pepm_frontend_local
